theme: jekyll-theme-minimal

title: Bev Wilson
locale: en_US
logo: #
description : &description "planning prof ğŸ‘¨ğŸ½â€ğŸ« data enthusiast ğŸ“Š banjo frailer ğŸª• purveyor of puns ğŸ˜‚"

  name: Navigate
  bio : "Your biography for the left-hand sidebar"
  avatar: bev_wilson_long.png
  email: bw6xs@virginia.edu
  # Do not include the @ symbol in your Twitter username
  linkedin: bev-wilson-aicp-0a00545
  github: bw6xs
  orcid: 0000-0003-3892-456X
  google:
    scholar: -y4JRccAAAAJ
