theme: jekyll-theme-minimal

title: Bev Wilson
locale: en_US
logo: #
description : &description 

  name             : "Navigate"
  bio              : "planning prof ğŸ‘¨ğŸ½â€ğŸ« data enthusiast ğŸ“Š banjo frailer ğŸª• purveyor of puns ğŸ˜‚"
  location         : "Charlottesville, Virginia"
  employer         :
  googlescholar    : "https://scholar.google.com/citations?user=-y4JRccAAAAJ&hl=en"
  email: bw6xs@virginia.edu
  linkedin: bev-wilson-aicp-0a00545
  github: bw6xs
  orcid: 0000-0003-3892-456X
